config/routes.rb
Rails.application.routes.draw do
	resources :users
	resources :pills
	resources :boxes

	namespace :api do
	  resources :pills
	end


	get 'pills/:id/remove' => 'pills#edit', as: :remove_pill

	patch  '/pills/:id'    =>  'pills#update'
	put    '/pills/:id'    =>  'pills#update'

	resources :pills do
		get "delete"
	end


	#signin and sign out paths
	get 'sign_in' => 'sessions#new', as: :sign_in
	post 'sign_in' => 'sessions#create'
	delete 'sign_in' => 'sessions#delete', as: :end_session
	get 'sign_out' => 'sessions#delete', as: :sign_out

	root to: 'pills#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :pills
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :pill
end

app/models/pill.rb
class Pill < ApplicationRecord
  belongs_to :box
  has_many :notifications
  scope :by_slot, -> (slot_number) {where(slot: slot_number)}
  SLOT = ['First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth', 'Seventh']

  def formatted_time
    formatted_time = time.strftime('%I:%M %p')
  end

  validates :slot, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :boxes
	has_many :pills, through: :boxes
	validates :email, presence: true, uniqueness: true
end

app/controllers/api/pills_controller.rb
class Api::PillsController < ApplicationController

  before_action do
    request.format = :json
  end

protect_from_forgery with: :null_session


  def index
      @pills = Pill.all
  end

  def show
      @pill = Pill.find_by id: params[:id]
      render json: @pill, status:201
  end

  def create
    @pill = Pill.create(pill_params)
    if @pill.save
      render :show, status: 201
    else
      render json: @pill.errors, status:422
    end
  end

  def new
    @pill = Pill.new(pill_params)
  end

  def update
    @pill = Pill.find_by id: params[:id]
    if @petition.update(petition_params)
      render :show
    else
      render json: @pill.errors, status: 422
    end
  end

  def delete
    @pill = Pill.find_by id: params[:id]
    @pill.destroy
    head :ok
  end

  private

  def pill_params
    params.require(:pill).permit(:slot, :drug, :dose, :time)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :null_session

   before_action do
      @current_user = User.find_by id: session[:user_id]
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController

  def show
   @box = Box.find(params[:id])
  end

  def new
   @box = Box.new
  end

  def create
   @boxes = Box.all
   @box = Box.create(box_params)
   
  end

  def edit
   @box = Box.find(params[:id])
  end

  def update
   @boxes = Box.all
   @box = Box.find(params[:id])

   @box.update_attributes(box_params)
  end

  def delete
   @box = Box.find(params[:box_id])
  end


  def destroy
   @boxes = Box.all
   @box = Box.find(params[:id])
   @box.destroy
  end

  private

  def box_params
   params.require(:box).permit(:user_id)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/pills_controller.rb
class PillsController < ApplicationController
  before_action :sign_in
  before_action do
     @current_user = User.find_by id: session[:user_id]
 end

  def index
   @pills = @current_user.pills.all.order(id: :asc)
   @first = @current_user.pills.by_slot("First").first
   @second = @current_user.pills.by_slot("Second").first
   @third = @current_user.pills.by_slot("Third").first
   @fourth = @current_user.pills.by_slot("Fourth").first
   @fifth =  @current_user.pills.by_slot("Fifth").first
   @sixth = @current_user.pills.by_slot("Sixth").first
   @seventh = @current_user.pills.by_slot("Seventh").first

  end


  def show
   @pill = Pill.find(params[:id])
  end


  def new
   @pill = Pill.new
  end

  def create
   @pills = Pill.all
   @pill = Pill.create(pill_params)
  end

  def edit
   @pill = Pill.find(params[:id])
  end

  def update
   @pills = Pill.all.order(id: :asc)
   @pill = Pill.find(params[:id])
   @pill.update_attributes(pill_params)
   MedsScheduledMailer.scheduled_email(@current_user, @pill).deliver_later
  end

  def delete
   @pill = Pill.find(params[:pill_id])
  end


  def destroy
   @pills = Pill.all
   @pill = Pill.find(params[:id])
   @pill.destroy
  end


  def remove
    @pill = Pill.find(params[:id])
    @pill.drug = ""
    @pill.dose = ""
    @pill.update_attributes(pill_params)
  end

  private
  def sign_in
   if @current_user.nil?
     redirect_to sign_in_path, alert: "Please Sign In"
   end
  end


  def pill_params
   params.require(:pill).permit(:drug, :dose, :time, :slot, :box_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Signed in!"
    else
      flash.now[:alert] = "Something is wrong with your username and/or password"
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Signed Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show,  :edit, :update, :destroy]
 before_action :secure, only: [:show,  :edit, :update, :destroy]

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)

    respond_to do |format|
    if @user.save
      session[:user_id] = @user.id
      # Sends email to user when user is created.
      HelloMailer.hello_email(@user).deliver_later

      @box = @user.boxes.build
      @box.save

      @first = @box.pills.build(slot: "First")
      @first.save
      puts @first.slot

      @second = @box.pills.build(slot: "Second")
      @second.save
      puts @second.slot

      @third = @box.pills.build(slot: "Third")
      @third.save
      puts @third.slot

      @fourth = @box.pills.build(slot: "Fourth")
      @fourth.save
      puts @fourth.slot

      @fifth = @box.pills.build(slot: "Fifth")
      @fifth.save
      puts @fifth.slot

      @sixth = @box.pills.build(slot: "Sixth")
      @sixth.save
      puts @sixth.slot

      @seventh = @box.pills.build(slot: "Seventh")
      @seventh.save
      puts @seventh.slot


      format.html { redirect_to root_path, notice: 'Welcome! Your account has been created.' }
      format.json { render :show, status: :created, location: @user }
    else
      format.html { render :new }
      format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

	def edit

	end

	def update
		if @user.update(user_params)
			redirect_to dashboard_path, notice: "User details updated!"
		else
			render :edit
		end
	end

	def show

	end

	def index
		@users = User.all
	end



	private
	def user_params
		params.require(:user).permit(:email, :password_digest, :password_confirmation, :password, :name)
	end

	def set_user
		@user = User.find_by id: params[:id]
	end

	def secure
		if @current_user.nil?
			redirect_to sign_in_path, alert: "Please sign in."
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def hello
  end
end

app/helpers/api/pills_helper.rb
module Api::PillsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pills_helper.rb
module PillsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	 <a href="https://github.com/sdossettswift/">	 S  D O S S E T T  S W I F T </a>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="Brand" src="mark.png">
      </a>
    </div>
    
  </div>
  <ul class="nav navbar-nav navbar-right">
     <%if @current_user%>
     <li><%= link_to "Sign Out", sign_out_path %></li>
     <%else%>
     <%end%>
 </ul>
</nav>

app/views/layouts/_notices.html.erb
<% if notice %>
	<div class="alert alert-info" role="alert">
	    <%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class="alert alert-danger" role="alert">
		    <%= alert %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EllieGrid Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
        #warning-message { display: none; }
        @media only screen and (orientation:portrait){
            #wrapper { display:none; }
            #warning-message { display:block; }
        }
        @media only screen and (orientation:landscape){
            #warning-message { display:none; }
        }
    </style>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= render 'layouts/notices' %>
    <div id="warning-message">
        this website is only viewable in landscape mode
    </div>
    <div id="wrapper">
      <div class ="body">
          <%= yield %>
        </div>
    </div>

  
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pills/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Pill</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= @pill.drug%> </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Pill", remove_pill_path(@pill), method: :patch, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/pills/_edit.html.erb
<%= render "form" %>

app/views/pills/_form.html.erb
<div class="modal-dialog" id="myModal">
  <div class="modal-content">
    <%= form_for @pill, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :drug %>
          <%= f.text_field :drug %>
        </div>
        <div class="form-group">
          <%= f.label :dose, class: "control-label" %>
          <%= f.text_field :dose %>
        </div>
        <div class="form-group">
          <%= f.label :time %>
          <%= f.time_select :time, {minute_step: 15, ampm: true}%>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/pills/_index.html.erb
<% @pills.each do |pill| %>
  <tr>
    <td><%= pill.drug %></td>
    <td><%= pill.dose %></td>
    <td><%= link_to "Edit", edit_pill_path(pill), remote: true, class: "btn btn-default" %></td>
    <td><%= link_to "Delete", pill_delete_path(pill), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/pills/_new.html.erb
<%= render "form" %>

app/views/pills/_pill_slot_info.html.erb
<% if pill == nil%>
  <%= link_to "Add", new_pill_path, remote: true %>
<% else %>

  <%=  link_to '<i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>'.html_safe, edit_pill_path(pill), remote: true%>
  <span>  </span>
  <%= link_to '<i class="fa fa-minus-circle fa-3x" aria-hidden="true"></i>'.html_safe, remove_pill_path(pill),remote: true %>

  <h4><%=pill.drug %></h4>
  <h5><%=pill.dose %></h5>
  <h5><%=pill.formatted_time if pill.time.present? %></h5>

<% end %>

app/views/pills/_save.js.erb
$("ul.errors").html("")
<% if @pill.errors.any? %>
  <% @pill.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".pill-index").html("<%= escape_javascript(render 'index') %>")
  $("#pill-modal").modal("hide")
  $('#pill-modal').on('hidden', function () {
    document.location.reload();
  })

<% end %>

app/views/pills/create.js.erb
<%= render "save" %>

app/views/pills/destroy.js.erb
<%= render "save" %>
window.location.reload()

app/views/pills/edit.js.erb
$("#pill-modal").html("<%= escape_javascript(render 'edit') %>")
$("#pill-modal").modal("show")

app/views/pills/index.html.erb
<div id="pill-modal" class="modal fade"></div>

<div class="container">
  <div class="row">
    <div class="col-xs-3 pill topLeft">
      <%= render 'pill_slot_info', pill:  @first %>
    </div>
    <div class="col-xs-3 pill">
      <%= render 'pill_slot_info', pill:  @second%>
    </div>
    <div class="col-xs-3 pill">
      <%= render 'pill_slot_info', pill:  @third%>
    </div>
    <div class="col-xs-3 pill topRight">
      <%= render 'pill_slot_info', pill:  @fourth%>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 pill bottomLeft">
      <%= render 'pill_slot_info', pill:  @fifth %>
    </div>
    <div class="col-xs-4 pill">
      <%= render 'pill_slot_info', pill:  @sixth%>
    </div>
    <div class="col-xs-4 pill bottomRight">
      <%= render 'pill_slot_info', pill:  @seventh%>
    </div>

  </div>

</div>

app/views/pills/new.js.erb
$("#pill-modal").html("<%= escape_javascript(render 'new') %>")
$("#pill-modal").modal("show")

app/views/pills/remove.js.erb
$("#pill-modal").html("<%= escape_javascript(render 'delete') %>")
$("#pill-modal").modal("show")
$("#pill-modal").refresh

app/views/pills/update.js.erb
<%= render "save" %>
window.location.reload()

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |error| %>
	<p class="alert alert-danger">
	    <strong><%= error %></strong>
	</p>
	<% end %>
<% end %>

<%=simple_form_for @user do |f|%>
	<%= f.input :name%>
	<%= f.input :email%>

	<div class="form-group">
	    <%= f.label :password %>
	    <%= f.password_field :password, size: "60x12", class: "form-control" %>
	</div>
	<div class="form-group">
	    <%= f.label :password_confirmation %>
	    <%= f.password_field :password_confirmation, size: "60x12", class: "form-control" %>
	</div>

	<div class="form-group">
	    <%= f.submit class: "btn btn-raised btn-default" %>   or	<%= link_to 'Sign In', sign_in_path %>
	</div>

	<div class="form-group">

	</div>

<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit Account</h1>
	<%= render partial: 'form' %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
	<thead>
		<tr>
			<th>User Id</th>
			<th>Name</th>
			<th>Email</th>
			<th>Link</th>
		</tr>
	</thead>
	<tbody>
		<%@users.each do |user|%>
		<tr>
			<td><%= user.id%></td>
			<td><%= user.name%></td>
			<td><%= user.email%></td>
			<td><%= link_to 'More Info', user_path(id: user.id)%></td>
		</tr>
		<% end%>
	</tbody>
</table>

app/views/users/new.html.erb
<div class="container">
	<h1>Sign Up</h1>
	<%= render partial: 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1><%= @user.name%></h1>
	<%= link_to "Update User", edit_user_path%>
</div>

app/views/welcome/hello.html.erb
<h1>HI!</h1>
 <%= link_to "New Pill", new_pill_path, remote: true, class: "btn btn-primary" %>